---
- name: prepare
  block:
    - debug: msg='version 1.2.4'

    - name: update os
      dnf:
        name: "*"
        state: latest
        update_only: yes
        use_backend: dnf

    # - name: install python
    #   dnf:
    #     name:
    #       - python39
    #       - python39-pip
    #       - python39-setuptools
    #       - python2
    #       - python2-pip
    #     state: present

    # - name: create new links
    #   file:
    #     dest: "{{ item.dest }}"
    #     src: "{{ item.src }}"
    #     state: link
    #     force: true
    #   loop:
    #     - {src: /usr/bin/python3.9, dest: /usr/bin/python3}
    #     - {src: /usr/bin/python2.7, dest: /usr/bin/python}

    - name: disable firewall
      systemd:
        name: firewalld
        state: stopped
        enabled: false

    - name: set hostname
      hostname:
        name: "{{ hostname }}"

    - name: disable ipv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: 1
        state: present

    - name: disable selinux
      lineinfile:
        regexp: "^SELINUX=.*"
        line: "SELINUX=disabled"
        path: /etc/selinux/config
      register: selinux_state

    - name: install epel repo
      yum:
        name: oracle-epel-release-el8
        state: present

    - name: install packages
      yum:
        name:
          - bind-utils
          - lsof
          - tcpdump
        state: present

    - name: update oip and setuptools
      pip:
        executable: /usr/bin/pip3
        name:
          - pip
          - setuptools
        state: latest

    - name: install python modules
      pip:
        executable: /usr/bin/pip3
        name:
          - cryptography
        state: latest

    - name: reboot to shutdown selinux
      reboot:

    - name: create group apigee
      group:
        name: apigee
        gid: 200

    - name: create user apigee
      user:
        name: apigee
        uid: 500
        group: apigee

  when:
    - inventory_hostname in groups.apigee

  tags:
    - install_all
    - prepare
